
## Syntax in Org-mode

- https://orgmode.org/worg/org-tutorials/org4beginners.html[Org mode beginning at the basics]
- https://orgmode.org/worg/dev/org-syntax.html[Org Syntax (draft)]
- https://orgmode.org/worg/org-tutorials/index.html[Org tutorials]
- https://hyperpolyglot.org/lightweight-markup[Lightweight Markup: Markdown, reStructuredText, MediaWiki, AsciiDoc, Org-mode - Hyperpolyglot]

## Tutorial
- http://ergoemacs.org/index.html[Xah Emacs Site]
- https://github.com/redguardtoo/mastering-emacs-in-one-year-guide/blob/master/guide-zh.org[mastering-emacs-in-one-year-guide/guide-zh.org at master · redguardtoo/mastering-emacs-in-one-year-guide]
- https://book.emacs-china.org/[Master Emacs in 21 Days]
- https://emacstalk.github.io/podcast/005/[005. 与 Emacs 高手陈斌闲聊 Emacs – EmacsTalk]

## Install in WSL
- https://github.com/hubisan/emacs-wsl[hubisan/emacs-wsl: Install and run Emacs with the Windows Subsystem for Linux (WSL) in Windows 10.]
- https://gist.github.com/kiennq/0f3e65098725b1f9708da8c92972e705[Build emacs-snapshot on Ubuntu 18.04]
- https://emacsredux.com/blog/2020/09/23/using-emacs-on-windows-with-wsl2/[Using Emacs on Windows with WSL2 | Emacs Redux]
- https://www.emacswiki.org/emacs/GccEmacs[Gcc Emacs]
- https://elecming.medium.com/the-ultimate-emacs-hacking-tutorial-in-windows-10-wsl-2-2fc4e9a899b0[The Ultimate Emacs Hacking Tutorial in Windows 10 WSL 2]
- https://mobaxterm.mobatek.net/[MobaXterm free Xserver and tabbed SSH client for Windows]
- https://steinslab.io/archives/2082[使用 WSL2 + X11 转发 - 在 Windows10 中打造 GNU/Linux 学习生产环境 - Steins;Lab]
- https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps[Run Linux GUI apps with WSL | Microsoft Docs]
- https://www.youtube.com/watch?v=kC3eWRPzeWw[WSL: Run Linux GUI Apps - YouTube]
- 

### Install Compile Dependency

I have totally no idea what these dependency means. 

[source,bash]
----
sudo apt update
sudo apt install -y autoconf automake bsd-mailx dbus-x11 debhelper dpkg-dev \
    libacl1-dev libasound2-dev libdbus-1-dev libgif-dev libgnutls28-dev libgpm-dev \
    libgtk-3-dev libjansson-dev libjpeg-dev liblcms2-dev liblockfile-dev libm17n-dev \
    libncurses5-dev liboss4-salsa2 libotf-dev libpng-dev librsvg2-dev \
    libselinux1-dev libsystemd-dev libtiff-dev libxml2-dev libxpm-dev procps quilt \
    sharutils texinfo zlib1g-dev gvfs language-pack-en-base libasound2 libaspell15 \
    libasyncns0 libatk-bridge2.0-0 libatk1.0-0 libatspi2.0-0 libbrotli1 \
    libcairo-gobject2 libcairo2 libcanberra-gtk3-0 libcanberra-gtk3-module \
    libcanberra0 libcroco3 libdatrie1 libdb5.3 libdrm2 libegl1 libenchant1c2a \
    libepoxy0 libflac8 libfontconfig1 libfreetype6 libgbm1 libgdk-pixbuf2.0-0 \
    libgif7 libgl1 libglvnd0 libglx0 libgpm2 libgraphite2-3 libgstreamer-gl1.0-0 \
    libgstreamer-plugins-base1.0-0 libgstreamer1.0-0 libgtk-3-0 libgudev-1.0-0 \
    libharfbuzz-icu0 libharfbuzz0b libhyphen0 libice6 libicu66 libjansson4 \
    libjavascriptcoregtk-4.0-18 libjbig0 libjpeg-turbo8 liblcms2-2 liblockfile1 \
    libltdl7 libm17n-0 libnotify4 libnss-mdns libnss-myhostname libnss-systemd \
    libogg0 liborc-0.4-0 libotf0 libpango-1.0-0 libpangocairo-1.0-0 \
    libpangoft2-1.0-0 libpixman-1-0 libpng16-16 libpulse0 librsvg2-2 libsasl2-2 \
    libsecret-1-0 libsm6 libsndfile1 libsoup2.4-1 libssl1.1 libstdc++6 libtdb1 \
    libthai0 libtiff5 libvorbis0a libvorbisenc2 libvorbisfile3 libwayland-client0 \
    libwayland-cursor0 libwayland-egl1 libwayland-server0 libwebp6 libwebpdemux2 \
    libwoff1 libx11-6 libx11-xcb1 libxau6 libxcb-render0 libxcb-shm0 libxcb1 \
    libxcomposite1 libxcursor1 libxdamage1 libxdmcp6 libxext6 libxfixes3 libxi6 \
    libxinerama1 libxkbcommon0 libxml2 libxpm4 libxrandr2 libxrender1 libxslt1.1 \
    libyajl2

sudo add-apt-repository -y ppa:ubuntu-toolchain-r/ppa
sudo apt install -y autoconf make checkinstall texinfo libxpm-dev libjpeg-dev \
     libgif-dev libtiff-dev libpng-dev libgnutls28-dev libncurses5-dev \
     libjansson-dev libharfbuzz-dev libgccjit-10-dev gcc-10 g++-10
sudo apt update
sudo apt -y upgrade

sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 10
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 10
----
### Clone Emacs
[source,bash]
----
git clone -b master --single-branch --depth=1 https://github.com/emacs-mirror/emacs.git
cd emacs/
# Always install the latest version
git fetch origin master
----
### Compile

I have totally no idea what these code means. 

[source,bash]
----
./autogen.sh
./configure --with-json --with-modules --with-harfbuzz --with-compress-install \
            --with-threads --with-included-regex --with-zlib --with-cairo --with-rsvg\
            # WSLg supports sound, so you can turn it on. 
            --without-sound \
            --without-imagemagick  --with-toolkit-scroll-bars \
            --with-gpm --with-dbus  --with-pop \
            --with-mailutils \
            # If you use Gnome you should turn it on
            --without-gsettings \
            --with-native-compilation
make NATIVE_FULL_AOT=1 -j$(nproc)
sudo checkinstall -y -D --pkgname=emacs28-nativecomp --pkgversion=1$(git rev-parse --short HEAD) \
     --requires="libjansson-dev,libharfbuzz-dev,libgccjit-10-dev" --pkggroup=emacs --gzman=yes \
     make install-strip
----

### Install Fonts

https://medium.com/source-words/how-to-manually-install-update-and-uninstall-fonts-on-linux-a8d09a3853b0[How to Manually Install, Update, and Uninstall Fonts on Linux | by Chris Simpkins | Source Words | Medium]

[source,bash]
----
sudo apt install p7zip-full fonts-cascadia-code
sudo apt install p7zip-full
mkdir sarasa
cd sarasa
wget https://github.com/be5invis/Sarasa-Gothic/releases/download/v0.34.1/sarasa-gothic-ttf-0.34.1.7z
7z e sarasa-gothic-ttf-0.34.1.7z
# if there's no fonts, mkdir
mv *.ttf ~/.local/share/fonts
fc-cache -f -v
fc-list | grep "Sarasa"
----

### X Server

- https://github.com/microsoft/wslg[microsoft/wslg: Enabling the Windows Subsystem for Linux to include support for Wayland and X server related scenarios]

- https://www.zhihu.com/question/455956831[如何看待 Windows 10 Build 21364 支持直接在 WSL2 中运行 GUI 应用？ - 知乎]

The latest version of Windows has implemented a GUI distro layer. So a X server is no longer needed. 

But the border is really ugly. See the issue https://github.com/microsoft/wslg/issues/37[Default window decorations color · Issue #37 · microsoft/wslg]

#### Turn off WSLg

- https://github.com/microsoft/wslg[microsoft/wslg: Enabling the Windows Subsystem for Linux to include support for Wayland and X server related scenarios]

You can turn it `WSLg` off and use VcXsrv or XMing or MobaXTerm. 

> Users wanting to use different servers than the one provided by WSLg can change these environment variables. User can also choose to turn off the system distro entirely by adding the following entry in their `.wslconfig` file (located at `c:\users\MyUser\.wslconfig`). This will turn off support for GUI applications in WSL.

#### The border

- https://github.com/microsoft/wslg/issues/37[Default window decorations color · Issue #37 · microsoft/wslg]
- https://www.reddit.com/r/emacs/comments/b2r2oj/is_it_possible_to_disable_or_hide_the_titlebar_in/[Is it possible to disable or hide the titlebar in Emacs but still be able resize with the mouse? : emacs]

Just hide it by

[source,elisp]
----
  ;; Scroll bar behaviour is in 
  ;; dotspacemacs-smooth-scrolling 
  ;; dotspacemacs-scroll-bar-while-scrolling 
  (menu-bar-mode 1)
  (setq default-frame-alist '((undecorated . t)))
  (add-to-list 'default-frame-alist '(drag-internal-border . 1))
  (add-to-list 'default-frame-alist '(internal-border-width . 5))
----

#### Copy and Paste
- https://github.com/microsoft/wslg/issues/15[Cannot copy text *into* Kate editor, copying text *from* Kate works fine. · Issue #15 · microsoft/wslg]
- https://github.com/microsoft/wslg/issues/295[Add support for Windows clipboard shortcuts · Issue #295 · microsoft/wslg]
- https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-clipboard?view=powershell-7.1[Get-Clipboard (Microsoft.PowerShell.Management) - PowerShell | Microsoft Docs]
- https://www.gnu.org/software/emacs/manual/html_node/elisp/Formatting-Strings.html[Formatting-Strings]
- https://www.gnu.org/software/emacs/manual/html_node/elisp/Output-Functions.html[https://www.gnu.org/software/emacs/manual/html_node/elisp/Output-Functions.html]
- https://github.com/emacsmirror/xclip[emacsmirror/xclip: Copy&paste GUI clipboard from text terminal]
- https://github.com/rolandwalker/simpleclip[rolandwalker/simpleclip: Simplified access to the system clipboard in Emacs.]
- https://github.com/microsoft/wslg/issues/105[Neovim yank to xclip breaks wslg · Issue #105 · microsoft/wslg]

>  would you please check weston.log at /mnt/wslg and do you still see massive below errors logged ? if not, would you please share weston.log captured right after the issue happened? thanks!

##### Spacemacs

- https://github.com/syl20bnr/spacemacs/commit/e4cb2b37dc79963c3f72e3f88f108fc4713ae65f[Add X clipboard support layer to terminal emacs. · syl20bnr/spacemacs@e4cb2b3]
- https://develop.spacemacs.org/layers/+tools/xclipboard/README.html[xclipboard layer]
- https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Btools/xclipboard[spacemacs/layers/+tools/xclipboard at develop · syl20bnr/spacemacs]

[source,elisp]
----
dotspacemacs-configuration-layers '(
  (xclipboard
  :variables  xclipboard-copy-command "copy.exe"
              xclipboard-paste-command "paste.exe")
)
----

You have to check the source code to tell what's going on here. The documentation is really bad (2021/08/08)

###### Source Code

.a bash shell script detect the OS we're using? Or you need to set the the variables. 
[source,bash]
----
command_exists() {
    local command=\"$1\"
    type \"$command\" >/dev/null 2>&1
  }
  # Installing reattach-to-user-namespace is recommended on macOS.
  if command_exists \"pbcopy\"; then
      if command_exists \"reattach-to-user-namespace\"; then
          printf \"reattach-to-user-namespace pbcopy\"
      else
          printf \"pbcopy\"
      fi
  elif command_exists \"clip.exe\"; then # WSL clipboard command
      printf \"clip.exe\"
  elif command_exists \"xsel\"; then
      printf \"xsel -ib\"
  elif command_exists \"putclip\"; then # cygwin clipboard command
      printf \"putclip\"
  fi
----

- https://www.gnu.org/software/emacs/manual/html_node/emacs/Clipboard.html[https://www.gnu.org/software/emacs/manual/html_node/emacs/Clipboard.html]

.the implementation of Spacemacs
[source,elisp]
____
(defun spacemacs/xclipboard-copy ()
  "Copies selection to x-clipboard."
  (interactive)
  (if (display-graphic-p)
    (progn
      (message "Copied region to x-clipboard!")
      (call-interactively 'clipboard-kill-ring-save)) <1>
    (if (region-active-p)
      (progn
        (shell-command-on-region
         (region-beginning) (region-end)
         (format "DISPLAY=%s %s"
                 (spacemacs/xclipboard-get-display)
                 (spacemacs//xclipboard-get-copy-command)))
        (message (format "Copied region to clipboard \"%s\"!"
                         (spacemacs/xclipboard-get-display)))
        (deactivate-mark))
      (message "No region active; can't copy to clipboard!"))))
____
<1> It's the correct solution. You shoulden't just "pipe" to it directly. (or create a new process)
It will hang the clipboard. What you will get is `ERROR: UtilConnectUnix`. (Maybe?)

.the paste implementation of Spacemacs
[source,elisp]
____
(defun spacemacs/xclipboard-paste ()
  "Pastes from x-clipboard."
  (interactive)
  (if (display-graphic-p)
    (progn
      (clipboard-yank)
      (message "graphics active"))
    (insert (shell-command-to-string
             (format "DISPLAY=%s %s"
                     (spacemacs/xclipboard-get-display)
                     (spacemacs//xclipboard-get-paste-command)))))
  (message (format "Pasted from clipboard \"%s\"!"
                   (spacemacs/xclipboard-get-display))))
____




##### Code copy and pasted from Internet

Don't use these. They are *REALLY BAD*! (at least the part I wrote is really bad)
Please just refer to the source code from Spacemacs above

Although I wrote some of these function I have totally no idea
what they are doing. 

[source,elisp]
----
  ;; (push "~/.spacemacs.d/packages" load-path)

  ;; Run emacs wsl on GUI mode
  ;; From the start menu
  ;; instead of bash 'emacs'
  (defun wsl-copy-string (str)
    "pipe str to clip.exe"
    (start-process "wsl-clipboard" nil "clip.exe")
    (process-send-string "wsl-clipboard" str)
    (kill-process "wsl-clipboard"))
  ;; (async-shell-command (format "echo \"'%S'\" | clip.exe" str)))
  ;; (shell-command-to-string (format "echo "'%s'" | clip.exe" str)))

  ; wsl-copy
  (defun wsl-copy (start end)
    (interactive "r")
    ;; (let ((buffer (buffer-substring-no-properties start end)))
    ;;   (wsl-copy-string buffer))
    (shell-command-on-region start end "clip.exe")
    (deactivate-mark))
    ;; (shell-command-on-region start end "clip.exe")

  (defun wsl-get-clipboard ()
    "return a string from wsl clipboard"
    (interactive)
    (let (
          (clipboard (shell-command-to-string "powershell.exe -command 'Get-Clipboard' 2> /dev/null")))
      (setq clipboard (replace-regexp-in-string "\r" "" clipboard)) ; Remove Windows ^M characters
      (setq clipboard (substring clipboard 0 -1)) ; Remove newline added by Powershell
  ))
  ;; (shell-command-to-string "powershell.exe -command 'Get-Clipboard'")

  (defun wsl-paste-insert ()
    (interactive)
    (insert (wsl-get-clipboard)))

  (defun wsl-paste-replace (beg end)
    (interactive "r")
    (replace-region-contents beg end 'wsl-get-clipboard))

  (defun wsl-set-evil-c-register ()
    " Set evil register with a value from wsl clipboard
      a character is a question mark '?' following a char according to
      https://www.gnu.org/software/emacs/manual/html_node/elisp/Basic-Char-Syntax.html"
    (interactive)
    (evil-set-register ?c (wsl-get-clipboard)))

  (defun wsl-read-evil-c-register ()
    " Write the contents of c rigister to clipboard
      a character is a question mark '?' following a char according to
      https://www.gnu.org/software/emacs/manual/html_node/elisp/Basic-Char-Syntax.html"
    (interactive)
    (wsl-copy-string (evil-get-register ?c)))

  ;; (require 'cl-generic)

  (define-key evil-insert-state-map (kbd "C-v") 'wsl-paste-insert)
  (define-key evil-visual-state-map (kbd "C-v") 'wsl-paste-replace)
  (define-key evil-visual-state-map (kbd "C-c") 'wsl-copy)

----
