= Hello World Scala
:toc:

== Normal Way
Just like Java the old days. Although I hate Java. 

[source,scala]
----
object SayHello {
  def hello(msg:String): Unit = 
    println("Hello world!")
    println(msg)
  def main(args:Array[String]): Unit = {
    def msg = "I was compiled by Scala 3. :)"
    hello(msg)
    // this.hello(msg) also works
  }
}
----
== Extends App
https://stackoverflow.com/questions/11667630/difference-between-using-app-trait-and-main-method-in-scala[Difference between using App trait and main method in scala]
[source,scala]
----
object SayHello extends App{
  def main(args:Array[String]): Unit = {
    def msg = "I was compiled by Scala 3. :)"
    println("Hello world!")
    println(msg)
  }
}
----

== Scala 3 @main

- https://docs.scala-lang.org/scala3/book/methods-main-methods.html[MAIN METHODS]
- https://docs.scala-lang.org/scala3/book/scala-for-javascript-devs.html[SCALA FOR JAVASCRIPT DEVELOPERS]

[source,scala]
----
// Metals in VSCode will complaint, but it works! 
// ! try to import a build created by sbt in scala 3, Metals won't complaint! 
@main def hello: Unit = 
    println("Hello world!")
    println(msg)
def msg = "I was compiled by Scala 3. :)"
// val function and def method 
// Lambda function returned type is implicit
val hello:(String)=>Unit = (name:String) => {
  println("Hello "+name)
}

def def_hello:(String)=>Unit = (name:String) => {
  println("Hello "+name)
}
// You are writing JavaScript NOW!!!! (ES6 later)
----

== Multiple main

.Multiple main code
[source,scala]
----
object SayHello {
  def hello(msg:String): Unit = 
    println("Hello world!")
    println(msg)
  def main(args:Array[String]): Unit = {
    def msg = "I was compiled by Scala 3. :)"

    hello(msg)
  }
}

// Compiler will wrap a class within it
@main def hello: Unit = 
    println("Hello world!")
    println(msg)
def msg = "I was compiled by Scala 3. :)"
//End
----

.Compiler Output
----
[info] welcome to sbt 1.5.5 (Oracle Corporation Java 16.0.1)
[info] loading project definition from C:\Users\cross\Desktop\Scala\new_demo\project
[info] loading settings for project root from build.sbt ...
[info] set current project to scala3-simple (in build file:/C:/Users/cross/Desktop/Scala/new_demo/)
[info] compiling 1 Scala source to C:\Users\cross\Desktop\Scala\new_demo\target\scala-3.0.1\classes ...

Multiple main classes detected. Select one to run:
 [1] SayHello
 [2] hello

Enter number: 2
[info] running hello
Hello world!
I was compiled by Scala 3. :)
----



== Links
- https://stackoverflow.com/questions/49706714/curly-braces-in-scala-method-call[Curly braces in Scala method call]
- https://ammonite.io/[Ammonite]
- https://docs.scala-lang.org/overviews/scala-book/hello-world-1.html
- https://stackoverflow.com/questions/18887264/what-is-the-difference-between-def-and-val-to-define-a-function
- https://docs.scala-lang.org/style/method-invocation.html
- https://docs.scala-lang.org/scala3/new-in-scala3.html

= Others
https://docs.scala-lang.org/scala3/book/taste-control-structures.html[CONTROL STRUCTURES]

.Start with the Weird Object
[source,scala]
----
object Hello {
  def msg = "I was compiled by Scala 3. :)"
  def hello(): Unit = 
    println("Hello world!")
    println(msg)
  def main(args:Array[String]) = {
    hello()
    println("Surprise!")
  }
  println("I'm Outside of the world, I'm the first one to be execute! ")
}
----

== Function with/without parenthesis
- https://www.scala-lang.org/api/2.13.3/scala/collection/immutable/Range$$Inclusive.html
- https://stackoverflow.com/questions/7409502/what-is-the-difference-between-def-foo-and-def-foo-in-scala
[source,scala]
----
def hello() 
hello 
// [error] method hello in object Hello must be called with () argument 

def hello
hello()
// [error] method hello in object Hello does not take parameters 

// def hello and call hello is okay
// def hello() and call hello() is okay as well

// How do we separate method and property? 

(1 to 10).toList()
// missing argument for parameter n of method apply in trait LinearSeqOps: (n: Int): Int
(1 to 10).toList
// val res5: List[Int] = List(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

('a' to 'd').toList
// val res8: List[Char] = List(a, b, c, d) 
// It's a good iterator
// Actually, it's just an ascii convertor
----

== Indentation
- https://docs.scala-lang.org/scala3/reference/other-new-features/indentation.html

== Control Flow
- https://docs.scala-lang.org/scala3/reference/other-new-features/indentation.html
- https://docs.scala-lang.org/scala3/book/taste-control-structures.html

[source,scala]

=== for loop
[source,scala]
----
1 to 10
//  [1,10]:Domain
1 until 10
//  [1,10):Domain => [1,9]:Domain
1 to 10 by 2
// Range(1, 3, 5, 7, 9)
----

.Scala 2 C style
[source,scala]
----
for (i <- 1 to 10 if (i > 5) ) {println(i)}
----

.Scala 3 omit brace and parenthesis
[source,scala]
----
for i <- 1 to 10 if i > 5 do println(i)
----

=== if statement in a expression
.Scala 3 one line
[source,scala]
----
val greater = if 5>10 || 1+1==2  then 50 else 30 //omit () and add "then" keyword
val greater = if (5>10 || 1+1==2) 50 else 30 // scala 2 you can't omit () 
----
That's amazing. Here's a longer version
[source,scala]
----
val greater = (()=>{
  if (5>10 || 1+1==2){
    50 
    // You can't return it explicitly
    // return outside method definition
  } else {
    30
  }
}) ()
----
Surprisingly, the similarity between Javascript and Scala is small in this expression. 

[source,javascript]
----
// you have to put you function in parenthesis, don't forget add parenthesis at last! 
const greater = (()=>{
  if (5>10 || 1+1==2){
    return 50
  } else {
    return 30
  }
}) ()
greater // and you have to call it to assign value the value (evaluate it) lazy evaluation? 
----

But it's surprisingly natural in lisp (clojure)
[source,clojure]
----
(def greater (if (or (> 5 10) (= (+ 1 1) 2)) 50 30))
----

.test if a number (10) is an even
[source,scala]
-----
var test = ((i:Int) => i%2 == 0)(10) //true
-----
=== Try/catch
[source,scala]
----
def toInt(str:String):Int={
  try{
    str.toInt
  }catch{
    // The last case _ is a “catch all” case for any other possible Int values. Cases are also called alternatives.
    // The default parameter is err already. 
    // err match { case ...}
    case _ : Throwable => 0
  }
}
----

=== Comprehension for/yield

Someone call it for Expression. 

- https://stackoverflow.com/questions/50398630/what-is-the-use-of-yield-in-scala-over-map
- https://docs.scala-lang.org/tour/for-comprehensions.html
- https://www.scala-lang.org/old/node/111
- https://zh.wikipedia.org/wiki/%E5%88%97%E8%A1%A8%E6%8E%A8%E5%AF%BC%E5%BC%8F
- https://zhuanlan.zhihu.com/p/28274410
- https://brilliant.org/wiki/list-comprehension/
- https://en.wikipedia.org/wiki/List_comprehension
- https://stackoverflow.com/questions/9061760/how-to-read-aloud-python-list-comprehensions

> “list comprehension”没有统一的中文译法。有译作列表解析式、列表生成式、列表构建、列表理解等。

> I initially called these ZF expressions, a reference to Zermelo-Frankel set theory — it was Phil Wadler who coined the better term list comprehension.

> A list comprehension is a construct available in some computer programming languages that allows the creation of lists from other lists. It uses set building notation to allow this functionality in an intuitive and elegant way.

> List comprehensions are a way to filter, transform, and combine lists. They're very similar to the mathematical concept of "set comprehensions". Set comprehensions are normally used for building sets out of other sets. 


还是用英文 list comprehension 比较好, 我觉得「列表解析」听起来也顺耳一点. 

for each member of seq(list), return the expression of yield, and then put it back. Basically it's a `map`. 

> A series of method calls that may include `map`, `flatMap`, `foreach` and `withFilter`

[source,scala]
----
abstract class CustomClass[A]{
  def map[B](f:A => B): CustomClass[B]
  def flatMap[B](f: A => CustomClass[B]): CustomClass[B]
  def withFilter(p: A => Boolean): CustomClass[A]
  def foreach(b: A => Unit): Unit // forEach is not a pure function
  // it doesn't return any value
}
----

.list comprehension in python
[source, python]
----
# I don't think we have definition in python
# one line python
num_list = [y for y in range(100) if y % 2 == 0 if y % 5 == 0]

# you can use multiple lines here
num_list = [y # yield (or return)
              for y in range(100) # generator
              if y % 2 == 0 # definition
              if y % 5 == 0 # definition
            ]
----

.list comprehension in scala
[source,scala]
----
val num_list = for {
  y <- 0 to 100
  if (y % 2 == 0)
  if (y % 5 == 0)
} yield y
----

==== Generators, filters and definitions

.list comprehension in scala
[source,scala]
----
for {
  p <- persons // Generator
  n = p.name // Definition
  if (n startsWith "To") // Filter
} yield
----

===== Generators
[source,scala]
----
  p <- persons // Generator
----
Every `for` comprehension begins with a generator, and can have multiple generators. 

==== Multiple Generator
Need `flatMap` function

把列表的列表弄平了 (拆分成最小的不可分元素, 然后碾平)

.map and flatMap
[source,scala]
----
def map[B](f:A => B): CustomClass[B]
Seq("apple","banana","orange").map(_.toUpperCase)
// Return
// 常识告诉我, 字符串是字符的列表
List(APPLE, BANANA, ORANGE)

def flatMap[B](f: A => CustomClass[B]): CustomClass[B]
Seq("apple","banana","orange").flatMap(_.toUpperCase)
// Return
List(A, P, P, L, E, B, A, N, A, N, A, O, R, A, N, G, E)

// The explain here is the return of function, which is the param of map/flatMap is differen
// How? What I pass is the same function
// flatten -- converts a "list of lists" to a single list. 
----

.multiple generator
[source,scala]
----
for { 
    y <- 0 to 10 // [0,10]:Domain
    x <- 11 to 20 by 2 // [11,13,15,17,19]
  } yield y
// Return
Vector( 0, 0, 0, 0, 0,
        1, 1, 1, 1, 1,
        2, 2, 2, 2, 2,
        ........
        10, 10, 10, 10, 10)

for { 
    x <- 11 to 20 by 2 // [11,13,15,17,19]
    y <- 0 to 10 // [0,10]:Domain
  } yield y
Vector( 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
        0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
        0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
        0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
        0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 )

for { 
      y <- 0 to 10 // [0,10]:Domain
      x <- 11 to 20 by 2 // [11,13,15,17,19]
    } yield x
Vector( 11, 13, 15, 17, 19, 
        11, 13, 15, 17, 19, 
        11, 13, 15, 17, 19, 
        ........
        11, 13, 15, 17, 19 )

for { 
    x <- 11 to 20 by 2 // [11,13,15,17,19]
    y <- 0 to 10 // [0,10]:Domain
  } yield x
Vector( 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
        13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
        15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
        17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17,
        19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19 ) 

for {
      y <- 0 to 10 // [0,10]:Domain
      x <- 11 to 20 by 2 // [11,13,15,17,19]
    } yield y * x
Vector( 0, 0, 0, 0, 0,        // y * x = 0 * x
        11, 13, 15, 17, 19,   // y * x = 1 * x
        22, 26, 30, 34, 38,   // y * x = 2 * x
        33, 39, 45, 51, 57,   // y * x = 3 * x
        ......
        110, 130, 150, 170, 190) // y * x = 10 * x

for { 
      x <- 11 to 20 by 2 // [0,10]:Domain
      y <- 0 to 10 // [11,13,15,17,19]
    } yield y * x
Vector( 0, 11, 22, 33, 44, 55, 66, 77, 88, 99, 110,
        0, 13, 26, 39, 52, 65, 78, 91, 104, 117, 130,
        0, 15, 30, 45, 60, 75, 90, 105, 120, 135, 150,
        0, 17, 34, 51, 68, 85, 102, 119, 136, 153, 170,
        0, 19, 38, 57, 76, 95, 114, 133, 152, 171, 190 )
----

Generator(s) 的顺序极其重要. 就像一个被压扁的 `row * col` (前一个出现的 Generator 是 row, 后一个是 col) 的矩阵

当然就算搞反了其实也就转置的事


===== Filters
[source,scala]
----
  if (n startsWith "To") // Filter
----

===== Definition
[source,scala]
----
  n = p.name // Definition
----
Temp variables. 

.for/yield in scala
[source,scala]
----
scala> for (i <- 1 to 5) yield i
// res0: scala.collection.immutable.IndexedSeq[Int] = Vector(1, 2, 3, 4, 5)
scala> for (i <- 1 to 5) yield i * 2
// res1: scala.collection.immutable.IndexedSeq[Int] = Vector(2, 4, 6, 8, 10)

// some functions in yield
def my_int_map[A](f:(Int)=>A,seq:Seq[Int]):Seq[A] = {
  for x <- seq yield f(x)
}
def my_generic_map[A,B](f:(B)=>A,seq:Seq[B]):Seq[A] = {
  for x <- seq yield f(x)
}
def my_generic_filter[A,B](f:(B)=>Boolean,seq:Seq[B]):Seq[B] = {
  for x <- seq if f(x) == true yield x
}
def filter_and_map[A,B](f_filter:(B)=>Boolean,f_map:(B)=>A,seq:Seq[B]) = {
  for x <- seq if f_filter(x) == true yield f_map(x)
}

// scala> filter_and_map((_:Int) > 2, (_:Int) * 2, List(-1,-2,-3,5,3,2))
// val res1: Seq[Int] = List(10, 6)
----


== Anonymous function
You must *ANNOTATE* THE TYPE of low dash (input parameter)

.like clojure
[source,scala]
----
filter_and_map((_:Int) > 2, (_:Int) * 2, List(-1,-2,-3,5,3,2))
----

.like javascript (arrow function)
[source,scala]
----
filter_and_map((x:Int)=> x > 2, (x:Int)=> x * 2, List(-1,-2,-3,5,3,2))
----

See <<Call by name>> and https://stackoverflow.com/questions/4386127/what-is-the-formal-difference-in-scala-between-braces-and-parentheses-and-when[What is the formal difference in Scala between braces and parentheses, and when should they be used?]


.function in bracket
[source,scala]
----
// def timer[A](f: => A): (A, Double)
timer((()=>1)())
// val res5: (Int, Double) = (1,0.01039)
timer{1}
// val res6: (Int, Double) = (1,8.3E-4)

timer{println("fuck")}
// fuck
// val res8: (Unit, Double) = ((),0.04058)

timer(println("fuck"))
// fuck
// val res9: (Unit, Double) = ((),0.03641)

timer((()=>println("fuck"))())
// fuck
// val res10: (Unit, Double) = ((),0.04276)
----

== Omit Braces and Parenthesis
- https://docs.scala-lang.org/scala3/reference/other-new-features/control-syntax.html
- https://stackoverflow.com/questions/1181533/what-are-the-precise-rules-for-when-you-can-omit-parenthesis-dots-braces-f

== implicit return
- https://stackoverflow.com/questions/12560463/return-in-scala



[quote]
It's not as simple as just omitting the return keyword. In Scala, if there is no return then the last expression is taken to be the return value. So, if the last expression is what you want to return, then you can omit the return keyword. But if what you want to return is not the last expression, then Scala will not know that you wanted to return it.

== Functional Programming
FP, series of expressions; Expression-Oriented Programming. (EOP)

[source,java]
-----
order.calculateTax()
order.updatePrices()
-----

They are statements because they don't have a return value. only executed for their side effects. 


[source,scala]
-----
val tax = calculateTax(order)
val price = calculatePrice(order)
-----
=== Unix Pipe
Writing FP as being lick writing Unix pipeline commands.

- Data stays at rest unless moved by a process
- Processes cannot consume or create data
- Must have a least one input data flow 
- Must have at least one output data flow

> avoiding black holes and miracles

=== Function composition
[source,scala]
----
def combine[A,B,C] (f1: A=>B, f2: B=>C): A => C = f1 andThen f2
----

https://clojuredocs.org/clojure.core/comp

=== Identity function
[source,scala]
----
def identity[A] (f: A) = f
----

=== List and recursion
- https://stackoverflow.com/questions/41346590/lists-in-scala-plus-colon-vs-double-colon-vs
- https://www.scala-lang.org/api/current/scala/collection/immutable/List.html[List]
- https://clojuredocs.org/clojure.core/rest
- https://en.wikipedia.org/wiki/CAR_and_CDR


.The custom sum function
[source,scala]
----
// val test = 1 :: 2 :: 3 :: Nil
// test.head == 1
// test.tail == List(2,3)
def sum_recursion(list: List[Int]): Int = {
  // the sum of a list is the sum of the head elem + the sum of the tail elems

  // pattern matching is popular in recursion

  // Nil == List() (empty List)
  list match
    case Nil => 0
    // case List() => 0
    case head :: tail => head + sum_recursion(tail)
    // case x :: xs => x + sum(xs) is more commonly used
    // x is for one instance and xs stand for more x! 
    // this patten matching is just like 
    // rest in clojure
}
----

[source,clojure]
----
(defn sum_recursion
  "it's a recursion version of sum"
  [list]
  (case list
    [] 0
    ;; the default behavior is no test condition
    ;; which is different from (cond)
    ;; which uses :else keyword
    (+ (first list) (sum_recursion (rest list)))))

;; a clear way to use let
(defn sum_recursion
  "it's a recursion version of sum"
  [list]
  (let [x (first list)
        xs (rest list)]
  ;; maybe
  ;; (let [ [x & xs] list ] ...)
  (case list
    [] 0
    (+ x (sum_recursion xs)))))
----
=== Tail recursion
[source,scala]
----
// code won't compile unless it's a tail recursion
// Cannot rewrite recursive call: it is not in tail position
@tailrec
def sum_acc(list: List[Int],acc:Int): Int = {
  list match
    case Nil => 0
    case x :: xs => sum_acc(xs, acc + x)
}
// use this as public api
// "0" in here just a "seed" value
def sum_tail_recursion(list: List[Int]): Int = sum_acc(list, 0)
----

.Alias for prepended (add (something) to the beginning of something else)
[source,scala]
----
final def +:[B >: A](elem: B): List[B]
----

.Alias for prepended
[source,scala]
----
final def +:[B >: A](elem: B): List[B]
----

[source, scala]
----
val list = List(1,2,3)

// list con ends with "Nil"
val list = 1 :: 2 :: 3 :: Nil
----

==== CAR and CDR
- https://en.wikipedia.org/wiki/CAR_and_CDR[CAR and CDR]
- https://www.gnu.org/software/emacs/manual/html_node/eintr/car-cdr-_0026-cons.html[Fundamental Functions]
- https://stackoverflow.com/questions/29907440/difference-between-cdr-car-and-rest-first-and-possible-implementation[Difference between CDR, CAR and REST, FIRST and possible implementation?]

> The operations `car` and `cdr` signals that you are working on a data structure build with pairs, that potentially isn't a list.

The `cons` function is used to construct lists, and the `car` and `cdr` functions are used to take them apart.

The `CAR` of a list is, quite simply, the **first** item in the list. 

The `CDR` of a list is the **rest** of the list, that is, the cdr function returns the part of the list that follows the first item. 

- car ("contents of the address part of register number"),
- cdr ("contents of the decrement part of register number"),


== Map (hashmap) in Scala

[source,scala]
----
val a_example_of_map = Map(
  "a" -> 42
)
//equals
val a_example_of_map_2 = Map(
  ("a",42)
)
// Type is Map[String,Int]
// of course you can be crazy
----

https://medium.com/front-end-weekly/es6-map-vs-object-what-and-when-b80621932373[ES6 — Map vs Object — What and when?]
[source,js]
----
const a_example_of_map = {
  "a" : 42
} // Strictly, it's a Javascript Object
----
[source,scala]
----
val functions = Map(
  ("2x",(x:Int)=>x*2),
  ("3x",(x:Int)=>x*3)
)
// Type is Map[String,Int=>Int]
// functions("3x")(9) = 27
----

== def is not val

[source,scala]
----
def triple(x:Int)=x*3
val x3 = (x:Int) = x*3
----

== Polymorphism

[source,scala]
----
object StringTools {
  def toHexStr (num:Int) = {
    "%02x".formatted(num)
  }
  def toHexStr (str:String):Array[String] = {
    str.getBytes().map(num=>if(num < 0xff) "%02x".formatted(num) else "ff")
  }
  def toHexStr (coll:Seq[Int]):Seq[String] = {
    coll.map(num=>if(num < 0xff) "%02x".formatted(num) else "ff")
  }
  def calculateNmeaChecksum (str:String):Int = {
    str.getBytes().reduce((x:Byte,y:Byte)=>(x^y).toByte).toInt
  }
  def main(args:Array[String]) = {
    val msg = "GPDTM,W84,,0.0,N,0.0,E,0.0,W84"
    println(toHexStr(calculateNmeaChecksum(msg)))
  }
}
----

.clojure version (multimethod)
[source,clojure]
----
;; NMEA checksum
;; no star, no dollar sign, sum all the character between
(def msg "$GPDTM,W84,,0.0,N,0.0,E,0.0,W84*6F")
(def msg_nocs "GPDTM,W84,,0.0,N,0.0,E,0.0,W84")

(def msg_no_checksum (drop 1 (drop-last 3 (.getBytes msg))))
(apply str (map #(char %) msg_no_checksum))

;; you can use keywords as well
;; that's :number, :coll, :string
;; However it's not clojure standard
(defn is_what
  "know what the type of x is"
  [x](cond
       (number? x) :number
       (coll? x) :coll
       (string? x) :string
       :else :error))
(defmulti toHexStr is_what)
(defmethod toHexStr :string
  [str] (map #(format "%02x" %) (.getBytes str)))
(defmethod toHexStr :number
  [num] (format "%02x" num))
(defmethod toHexStr :coll
  [collection] (map #(format "%02x" %) collection))

(toHexStr 64)
(toHexStr "number")
(toHexStr [99,31,89])

;; cal checksum
(defn calChecksum
  "cal checksum from bytes"
  ;; [bytes](let[total (reduce + bytes)] (+ (bit-and 0xff total) (bit-shift-right total 8)))
  [bytes] (let [total (reduce bit-xor bytes)] (bit-and 0xff total)))
----
.clojure function overload
[source,clojure]
----
(defn my_waifu
  "When you want to greet someone and introduce your waifus
   you can use this function. "
  ([name] (str "Hi " name "."))
  ([name & my_rest_waifu]
   (str "Hi " name ". Here "
        (if (single? my_rest_waifu)
          (str "is my waifu " (last my_rest_waifu) ". ")
          (str "are my waifus " (clojure.string/join ", " (drop-last my_rest_waifu)) " and " (last my_rest_waifu) ". ")
      ;;  (str (apply str (map (fn [waifu] (str waifu ", ")) (drop-last my_rest_waifu))) " and " (last my_rest_waifu) ". ")
          ))))
(my_waifu "tanaka" "fubuki" "sendai" "Akibahara" "nobody knowing what she called")
(my_waifu "tanaka")
(my_waifu "tanaka" "fubuki")
----

== Generic
https://docs.scala-lang.org/tour/polymorphic-methods.html

See examples in <<Comprehension for/yield>>

== Call by name

- https://en.wikipedia.org/wiki/Evaluation_strategy
- https://docs.scala-lang.org/tour/by-name-parameters.html[By-name parameters]
- https://stackoverflow.com/questions/4543228/whats-the-difference-between-and-unit

By-name parameters are evaluated every time they are used. They won’t be evaluated at all if they are unused.

https://stackoverflow.com/questions/28876368/scala-by-name-parameter-on-a-anonymous-function

I want a timer like this 
[source,scala]
----
val time = (result,time) = timer(some_function:(I_DON_KNOW_INPUT_TYPE):DON_KNOW_RETURN_TYPE_AS_WELL)
----
How can I achieve this? 
[source,scala]
----
// Notice f:=>A is not legal. It's "f: => A" with a space
// You can say
// def timer[A] = (f: => A) => {...}
// like JavaScript
//// You just can't
// an identifier expected, but '=>' found
// Actually you can

// def timer[A](f: => A): (A, Double) = {
def timer[A]: (=> A) => (A,Double) = (f) => {
  val startTime = System.nanoTime
  val result = f
  val stopTime = System.nanoTime
  val delta = stopTime - startTime
  // return (result,delta/1E7)
  return (result,delta/1E7)
}
----

== Return multiple items
See <<Call by name>>, use tuple

The return signature is `(OutputType1,OutputType2,...)`

== Parameter group
https://en.wikipedia.org/wiki/Currying[Currying]

[source,scala]
----
def add (a:Int)(b:Int)(c:Int) = a + b + c
def add (a:Int,b:Int,c:Int) = a + b + c
----
=== Currying
[source,scala]
----
def f2(a: Int,b: Int) = a + b

def curried_f2 = (f2 _).currie
//equals 
def curried_f2(a: Int)(b: Int) = a + b
// def curried_f2: Int => Int => Int

def wrap (prefix:String, middle:String, suffix:String) = prefix + html + suffix
def wrap_div = wrap("<div>", _:String, "/dev") // low dash:Type is usable in normal function and curried function
wrap("Hello World")
----

https://docs.scala-lang.org/tour/by-name-parameters.html[a custom while loop with by-name parameters]

.a custom while loop
[source,scala]
----
def my_while(f_test: => Boolean) (f_do: => Unit):Unit = {
  if (f_test == true){
    f_do
    my_while(f_test)(f_do) // recursion is just like JUMP in assembly? 
  }
}
----
== implicit parameter/value
When you need to refer to a shared resource serval times. 

[source,scala]
----
implicit val b = true
----

== Default value
[source,scala]
----
def f2 (a:Int = 0, b:Int = 0) = a + b
def f3(a:Int = 0)(b:Int = 0) = a + b
// the second para can refer to the first one
def f4(a:Int = 0)(b:Int = a) = a + b
----


== Bind
Rebinding doesn’t mutate the existing memory location. It reserves new memory and reassigns the symbolic name to the new location.

You should always keep in mind that data is immutable. Once a memory location is occupied with data, it can’t be modified until it’s released. But variables can be rebound, which makes them point to a different memory location. Thus, variables are mutable, but the data they point to is immutable.

If a function has no arguments, you can omit the parentheses in Elixir

Elixir comes with a built-in operator, `|>`, called the _pipeline operator_

= Terminology
- FIP function input parameter
- PAF partially applied function

== No exception in pure function
Function signature shouldn't tell a lie. 

> Pure functions never throw exceptions

> Pure function signatures are a contract with its consumers

=== The Option Class
- https://www.scala-lang.org/api/current/scala/Option.html
- https://www.baeldung.com/scala/option-type
- https://www.runoob.com/scala/scala-options.html
- https://www.runoob.com/w3cnote/scala-option-some-none.html

> Option 有两个子类别，Some 和 None。当程序回传 Some 的时候，代表这个函式成功地给了你一个 String，而你可以透过 get() 函数拿到那个 String，如果程序返回的是 None，则代表没有字符串可以给你。
> 在返回 None，也就是没有 String 给你的时候，如果你还硬要调用 get() 来取得 String 的话，Scala 一样是会抛出一个 NoSuchElementException 异常给你的。 我们也可以选用另外一个方法 getOrElse。这个方法在这个 Option 是 Some 的实例时返回对应的值，而在是 None 的实例时返回传入的参数。换句话说，传入 getOrElse 的参数实际上是默认返回值。

It's just `T | None`

.Scala represents optional values
[source]
----
          Option[T]
            ^
            |
    +-------+------+
    |              |
    |              |
  Some[T]        None[T]
----

=== Try, Success and Failure
When you want to let consumers of your code know *why* something failed, use `Try` instead of `Option`

=== Either, Left anad Right
- https://colobu.com/2015/06/11/Scala-Either-Left-And-Right/
- https://windor.gitbooks.io/beginners-guide-to-scala/content/chp7-the-either-type.html[这里面提到的设计缺陷已经被修正]

- `Left` holds the error
- `Right` holds the success value

It's unbiased prior to Scala 2.12. 
=== Or in Scalatic
https://www.scalactic.org/user_guide/OrAndEvery

=== "null" in Java
Convert them to "None". Like the error handle above. 

|===
|Base Type | Success Case | Failure Case

| Option | Some | None

| Try | Success | Failure 
| Or | Good | Bad 
| Either | Right | Left

|=== 